### ISSUE TITLE
[Feature Request]:  validation to remove tags from template if the values are empty

### ISSUE THREAD

**Issue by aishwrya** [carboneio/carbone#130]
**Problem to solve**
I do not want to render the tags which are empty in the template. For ex. If I have a tag {d.name} and if name is having an empty value then in the pdf that line is going to be blank. 

**Proposed solution**
Instead of making blank spaces in the pdf. If validations can be done to remove the tags from the template if its empty would be nice. Is there an existing solution for this?

**Comment by steevepay** [comment]
Hello @aishwrya,

Did you try to use a conditional block to hide or sho the tag?
Here is the documentation with examples:
https://carbone.io/documentation.html#conditioned-output

**Comment by atish-kumar-by** [comment]
for one tag it works fine but for consecutive tag not working fine.
{d.streetAddressOne}{d.streetAddressTwo:ifEM():hideBegin()}
{d.streetAddressTwo}{d.streetAddressTwo:ifEM():hideEnd()}{d. streetAddressThree:ifNEM():showBegin()}
{d.streetAddressThree}{d.
![Capture](https://user-images.githubusercontent.com/63335669/124142992-5d52cb00-daa8-11eb-90bc-1b824c212efa.JPG)
 streetAddressThree:ifNEM():showEnd()}

**Comment by steevepay** [comment]
Ending makers don't have to include the condition `ifEM`, you can simplify it into:
```
{d.streetAddressOne}{d.streetAddressTwo:ifEM():hideBegin}
{d.streetAddressTwo}{d.streetAddressTwo:hideEnd}{d. streetAddressThree:ifNEM():showBegin}
{d.streetAddressThree}{d. streetAddressThree:showEnd}
```
Let me know how it goes on your side.

**Comment by atish-kumar-by** [comment]
> Ending makers don't have to include the condition `ifEM`, you can simplify it into:
> 
> ```
> {d.streetAddressOne}{d.streetAddressTwo:ifEM():hideBegin}
> {d.streetAddressTwo}{d.streetAddressTwo:hideEnd}{d. streetAddressThree:ifNEM():showBegin}
> {d.streetAddressThree}{d. streetAddressThree:showEnd}
> ```
> 
> Let me know how it goes on your side.

if both streetAddress2 and streetAdrees3 is missing then we will get two empty line

**Comment by steevepay** [comment]
I don't have any extra empty lines with the expression I shared. Make sure you have inserted **break lines** (shift + enter) at the following places:
<img width="674" alt="Screenshot 2021-07-12 at 14 33 09" src="https://user-images.githubusercontent.com/16964532/125288524-88e27a80-e31e-11eb-91ae-f8049a8d179d.png">

**Comment by tom-schneider-by** [comment]
@steevepay This is good information.  Can you explain why this works?  How is this affecting the generated word XML?  I'm still not clear on why this would resolve this issue.

**Comment by steevepay** [comment]
Hello @tom-schneider-by,
We have to differentiate 2 ways to create a  new line:
- **New-line**: Close the current paragraph and open a new one, the standard "command" is the `Enter` key. Creating a new paragraph insert automatically a new line. For an ODT document, the XML looks like this:
```xml
<text:p text:style-name="P1">
      <text:span text:style-name="T2">Paragraph 1</text:span>
  </text:p> // BREAK LINE JUST HERE
  <text:p text:style-name="P1">
      <text:span text:style-name="T2">Paragraph 2</text:span>
  </text:p>
```
The XML is getting complex and Carbone has to move and reorder XML parts, which may leave newlines on the final report. Example of XML:
<img width="1023" alt="Screenshot 2021-07-13 at 10 41 49" src="https://user-images.githubusercontent.com/16964532/125420875-6f65c5c7-bc86-4c92-b85f-6749ec9d5790.png">

- **Break-line**: The new line is part of the current paragraph, hit `shift` + `Enter`, the XML looks like this:
```xml
  <text:p text:style-name="P2">
      <text:span text:style-name="T3">Text 1<text:line-break/>Text 2</text:span>
  </text:p>
```
Carbone removes `<text:line-break/>` XML tags pretty easily without reordering XML because everything is in the same paragraph:
```xml
<text:p>
        <text:span>{d.streetAddressOne}{d.streetAddressTwo:ifEM():hideBegin}<text:line-break/>
{d.streetAddressTwo}{d.streetAddressTwo:hideEnd}{d. streetAddressThree:ifNEM():showBegin}<text:line-break/>
{d.streetAddressThree}{d. streetAddressThree:showEnd}</text:span>
    </text:p>
```
As a conclusion, when using conditional formatters `showBegin/showEnd` or `hideBegin/hideEnd`, I just recommend inserting Break-lines with `shift` + `Enter`.
I am going to add those missing details to the Carbone documentation.
Feel free to reopen the issue if you got further questions, in the meantime, have a great day!
