### ISSUE TITLE
[Bug Report]: problems when using more than one <p> tag and also with <p></p>

### ISSUE THREAD

**Issue by whschopke98** [carboneio/carbone#162]
I am using carbone studio and a .docx template to generate a report.
Some objects in the json file are texts that should have one or more paragraphs, so I tried using the `<p>` tag and the :html formatter to include them in the rendered text.
It works well when only one `<p>` tag is used, but when I use more, only the first one is acknowledged while the others are just ignored.
Example1:
json:
`{
  "description" : "P1<p>P2<p>P3<p>P4"
}`

rendered text:
P1
P2P3P4

Seeing this, I thought that maybe it was necessary to use both `<p></p>` tags to include multiple paragraphs. I tried it, but this time the render added an extra paragraph between the ones I wanted.
Example2:
json:
`{
  "description" : "<p>P1</p><p>P2</p><p>P3</p><p>P4</p>"
}`

rendered text:
P1

P2

P3

P4

I'll attach the files used and the result.
[Result.docx](https://github.com/carboneio/carbone/files/8691552/Result.docx)
[Template.docx](https://github.com/carboneio/carbone/files/8691554/Template.docx)
[testing.txt](https://github.com/carboneio/carbone/files/8691559/testing.txt)

**Comment by steevepay** [comment]
Hello @whschopke98, thank you for your feedback!

For your first case, the `:html` formatter does render only paragraphs with a starting and ending tag `<p>...</p>`. I do confirm, If an ending tag is missing, other paragraphs tags are ignored because it is expecting an ending tag. We don't plan to change this logic for now. I would recommend you to always create starting and ending tags for all markers, except for `<br>`.

For the second case, the html expression `<p>P1</p><p>P2</p><p>P3</p><p>P4</p>` is rendered as expected. The HTML formatter render HTML into the native XML DOCX/ODT formats, and you may find slight rendering differences as XML Open Document Specifications and HTML Web Specification are completely different. In the case of the paragraph HTML tags, paragraph are added bellow the HTML paragraph tag to replicate the bottom spacing of paragraph when it is rendered into a web browsers. 

I'm available if you got further questions :) Have a good day!

**Comment by whschopke98** [comment]
Hi @steevepay, thank you for the answer. 
I understood the reason why extra paragraphs are added, but that then leads to the question: how do I remove them so that the rendered text is what I want? I understand that in browsers the addition of extra space before and after the text are needed, but in Word (DOCX) the spacing is already defined in the template.
I have already tried to use line-breaks instead of paragraphs, but they also cause discrepancies, namely the lack of spacing between blocks of text (as expected since they aren't actual paragraphs).

So what should I do to have carbone render a text where P1,P2,P3 and P4 are treated as simple paragraphs? no extra spacing.
I trully appreciate the help.

**Comment by steevepay** [comment]
@whschopke98,
As the HTML formatter is focusing mainly on the visual rendering, to match as much as possible browsers rendering, the behavior of adding an extra paragraph is the default one and it is not possible to disable it for now.

**Comment by whschopke98** [comment]
I see, that is unfortunate. I'll try a different route to this problem then. 
In the meantime, please consider adding the possibility to disable the extra paragraphs in some future iteration of carbone.
