### ISSUE TITLE
Carbone with docker compose

### ISSUE THREAD

**Issue by paulsen-it** [carboneio/carbone#209]
I have installed carbone via Docker Compose as in the documentation and it works so far. But now there is a problem, I want to fill a TXT template with json data and get it back as a TXT file, all line feeds are removed and I wanted to use a custom formatter to insert these line breaks as a solution. But now I have the problem that I can't find a place where I have to put my ownFunctions.js so that carbone reads my own formatter.
I also have no access to certain directories, as the user Carbone is used in the container and the default root password is nowhere to be found.

**Comment by guillaume-carbone** [comment]
To use your own formatter, you should : 
Create a file named formatters.js under the plugin folder.

Write module.exports = { }, then insert your Javascript function between curly brackets: One function is equal to one formatter.
Here is the minimum code of a formatter:
function addText (d, text) {
  return d + text;
}
/**
 * Details:
 * "d" the tag value
 * "text" the first argument of the formatter
 * A value must be returned otherwise it will print nothing in the document.
 * Example usage: {d.value:addText(' euro')}
 */

I recommend that you then create your own docker image with our plugins.
